### ISSUE TITLE
Disk [assets] does not have a configured driver.

### ISSUE THREAD

**Issue by fpolli** [lucky-media/landtamic#37]
I installed Laravel 11 and Sail per the Laravel documentation, then Statamic into that, as directed by the Statamic documentation. I modified Statamic to enable pro and multisite mode, and made a user. I then installed Landtamic, ran npm i and npm run dev, and navigated to the app home url in my browser (Chrome), and received the title exception.

Stack trace:

[2024-10-27 17:55:14] local.ERROR: Disk [assets] does not have a configured driver. {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Disk [assets] does not have a configured driver. at laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php:137)
[stacktrace]
#0 laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(120): Illuminate\\Filesystem\\FilesystemManager->resolve()
#1 laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(83): Illuminate\\Filesystem\\FilesystemManager->get()
#2 laravel/framework/src/Illuminate/Support/Facades/Facade.php(358): Illuminate\\Filesystem\\FilesystemManager->disk()
#3 statamic/cms/src/Filesystem/Manager.php(31): Illuminate\\Support\\Facades\\Facade::__callStatic()
#4 laravel/framework/src/Illuminate/Support/Facades/Facade.php(358): Statamic\\Filesystem\\Manager->disk()
#5 statamic/cms/src/Assets/AssetContainer.php(320): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 statamic/cms/src/Support/FluentGetterSetter.php(109): Statamic\\Assets\\AssetContainer->Statamic\\Assets\\{closure}()
#7 statamic/cms/src/Support/FluentGetterSetter.php(91): Statamic\\Support\\FluentGetterSetter->runGetterLogic()
#8 statamic/cms/src/Assets/AssetContainer.php(322): Statamic\\Support\\FluentGetterSetter->args()
#9 statamic/cms/src/Assets/AssetContainer.php(492): Statamic\\Assets\\AssetContainer->disk()
#10 statamic/cms/src/Assets/AssetContainer.php(502): Statamic\\Assets\\AssetContainer->accessible()
#11 statamic/cms/src/Assets/AssetContainer.php(137): Statamic\\Assets\\AssetContainer->private()
#12 statamic/cms/src/Assets/AssetRepository.php(81): Statamic\\Assets\\AssetContainer->url()
#13 laravel/framework/src/Illuminate/Collections/Collection.php(1515): Statamic\\Assets\\AssetRepository->Statamic\\Assets\\{closure}()
#14 laravel/framework/src/Illuminate/Collections/Collection.php(1607): Illuminate\\Support\\Collection->sortBy()
#15 statamic/cms/src/Assets/AssetRepository.php(80): Illuminate\\Support\\Collection->sortByDesc()
#16 statamic/cms/src/Assets/AssetRepository.php(47): Statamic\\Assets\\AssetRepository->resolveContainerFromUrl()
#17 statamic/cms/src/Assets/AssetRepository.php(41): Statamic\\Assets\\AssetRepository->findByUrl()
#18 laravel/framework/src/Illuminate/Support/Facades/Facade.php(358): Statamic\\Assets\\AssetRepository->find()
#19 statamic/cms/src/Tags/Asset.php(48): Illuminate\\Support\\Facades\\Facade::__callStatic()
#20 [internal function]: Statamic\\Tags\\Asset->index()
#21 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1608): call_user_func()
#22 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#23 statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#24 statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#25 statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#26 laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get()
#27 laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#28 laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#29 statamic/cms/src/Tags/Partial.php(29): Illuminate\\View\\View->render()
#30 statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render()
#31 statamic/cms/src/Tags/Tags.php(152): Statamic\\Tags\\Partial->wildcard()
#32 [internal function]: Statamic\\Tags\\Tags->__call()
#33 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1608): call_user_func()
#34 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#35 statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#36 statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#37 statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#38 laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get()
#39 laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#40 laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#41 statamic/cms/src/Tags/Partial.php(29): Illuminate\\View\\View->render()
#42 statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render()
#43 statamic/cms/src/Tags/Tags.php(152): Statamic\\Tags\\Partial->wildcard()
#44 [internal function]: Statamic\\Tags\\Tags->__call()
#45 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1608): call_user_func()
#46 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(2335): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#47 statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#48 statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#49 statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#50 statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#51 laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get()
#52 laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#53 laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#54 statamic/cms/src/View/View.php(104): Illuminate\\View\\View->render()
#55 statamic/cms/src/Http/Responses/DataResponse.php(150): Statamic\\View\\View->render()
#56 statamic/cms/src/Http/Responses/DataResponse.php(42): Statamic\\Http\\Responses\\DataResponse->contents()
#57 statamic/cms/src/Structures/Page.php(420): Statamic\\Http\\Responses\\DataResponse->toResponse()
#58 laravel/framework/src/Illuminate/Routing/Router.php(902): Statamic\\Structures\\Page->toResponse()
#59 laravel/framework/src/Illuminate/Routing/Router.php(887): Illuminate\\Routing\\Router::toResponse()
#60 laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Routing\\Router->prepareResponse()
#61 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#62 statamic/cms/src/StaticCaching/Middleware/Cache.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 statamic/cms/src/StaticCaching/Middleware/Cache.php(59): Statamic\\StaticCaching\\Middleware\\Cache->handleRequest()
#64 laravel/framework/src/Illuminate/Cache/Lock.php(131): Statamic\\StaticCaching\\Middleware\\Cache->Statamic\\StaticCaching\\Middleware\\{closure}()
#65 statamic/cms/src/StaticCaching/Middleware/Cache.php(59): Illuminate\\Cache\\Lock->block()
#66 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#67 statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AuthGuard->handle()
#69 statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#71 statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\Localize->handle()
#73 statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\HandleToken->handle()
#75 statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StacheLock->handle()
#77 laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#79 laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#81 laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#83 laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#85 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#86 laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#88 laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#90 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#92 laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#93 laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#94 laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#95 laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#96 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#97 statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#98 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#99 statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#100 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#101 statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#102 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#103 statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#104 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#105 statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#106 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#107 laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#108 laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#109 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#110 laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#111 laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#112 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#113 laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#114 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#115 laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#116 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#117 laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#118 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#119 laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#120 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#121 laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#122 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle()
#123 laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#124 laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#125 laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#126 laravel/framework/src/Illuminate/Foundation/Application.php(1188): Illuminate\\Foundation\\Http\\Kernel->handle()
#127 /var/www/html/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#128 laravel/framework/src/Illuminate/Foundation/resources/server.php(23): require_once('...')
#129 {main}

My install details:

Environment
Application Name: my app
Laravel Version: 11.29.0
PHP Version: 8.3.12
Composer Version: 2.8.1
Environment: local
Debug Mode: ENABLED
URL: myapp.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: pgsql
Logs: stack / single
Mail: log
Queue: database
Session: database

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 PRO

**Comment by fpolli** [comment]
As an update, I manually created a disk for assets in filesystems.php:

```
        'assets' => [
            'driver' => 'local',
            'root' => storage_path('app/public/assets'),
            'url' => env('APP_URL').'/assets',
            'visibility' => 'public',
            'throw' => false,
        ],
```
After doing that, I was able to get the Landtamic home page at my top-level domain (let's say myapp.test), but when I tried to go to /cp to login, I keep getting 302 directed to cp/dashboard and the below exception:

Call to undefined method App\Models\User::id()
```
resources/views/widgets/welcome.blade.php :25
            <div class="flex-1">
                <h2 class="text-blue-darkest">Configure Navigation</h2>
                <p>Add entries to the Navigation or Footer </p>
            </div>
        </a>
        <a href="{{ cp_route('users.edit', auth()->user()->id()) }}" class="flex items-start p-2 rounded-md hover:bg-blue-100 group">
```

I have made sure that the auth and users config files are edited as in the statamic docs for storing users in a database and have a super user created. After this error started, I did sail down -v and reran the migrations and created a new super user and the same thing happens. I made another test statamic install without Landtamic and as able to log into the cp as expected.

Thanks

**Comment by lokmanm** [comment]
@fpolli hey!

Sorry for the late response here, however looking from the logs looks like you haven't configured your disk on the Assets. 

We usually don't do support for things like this as its a Statamic issue and not a Landtamic one. If you need help with Statamic they have a Discord group you can join to ask questions.

As for the license, we don't manage those, you need to reach out to `support@statami.com` if you need help.

Thanks!

**Comment by fpolli** [comment]
Well, ok, but did you see my update where I DID configure a driver for assets and it DID work, then I ran into ANOTHER problem? You did not address that problem. Is that also a Statamic issue? Do you need me to break it out into a separate issue? Given that the license issue has me stuck here and it is your product I paid for, I would like to get some help with it and not just "not my problem go talk to the other guy."

Thanks.

**Comment by lokmanm** [comment]
Hey @fpolli,

I don't like your tone here, and we're definitely not required to provide live support, especially for Statamic questions.

I've already answered both of your questions in my previous reply, including your update.

If you have a license issue or want a refund, please reach out to Statamic.

I'm going to close this issue now.

**Comment by fpolli** [comment]
I am very disappointed in this response. I read your earlier response several times and never did I grasp that you also were addressing the user issue. It is very unclear.

Given your response to a frustrated customer, I am asking Statamic to refund my money. I wanted to use your product, but this support response tells me what to expect if I have future problems.

Very disappointing.

-------------
Fred Polli
Additional contact information available

**Comment by lokmanm** [comment]
@fpolli 

Landtamic does not change the user settings, thats something you configure either when installing or after. 

As I mentioned earlier, all your issues are related to Statamic itself and not Landtamic.

I would suggest you consult the documentation or the Discord group.

**Comment by lokmanm** [comment]
@fpolli that's because of the Eloquent driver, I will have to ask someone from the Core team if its an issue with the driver or if we should add a check for that `id` before outputting it.

The same code should work with both flat-files and database users.

**Comment by fpolli** [comment]
Thanks!

Statamic reset my license so I can start over. I think something was not quite right in my environment setup and initial install, and now I can try again. I was using Sail and now have my MacBook back and Herd set up, so I can do the conventional statamic new site install. Maybe it will go better this time.

-------------
Fred Polli
Additional contact information available
